Update requirements.txt
Issue during redeployment:
ERROR: Cannot install -r requirements.txt (line 5) and htmltools 0.5.3.9002 (from git+https://github.com/posit-dev/py-htmltools.git) because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested htmltools 0.5.3.9002 (from git+https://github.com/posit-dev/py-htmltools.git)
    shiny 1.1.1.dev44 depends on htmltools 0.5.3.9002 (from git+https://github.com/posit-dev/py-htmltools@main)

Altering requirements to use git+https://github.com/posit-dev/py-htmltools@main as required by shiny.